# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
    push:
        branches:
            - master
            - 'fix/**'
            - 'enhancement/**'
    pull_request:
        branches:
            - master
            - 'fix/**'
            - 'enhancement/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [12.x]

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v2

            - name: Run a one-line script
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}

            - run: npm install

            - run: npm run code:format

            - run: npm run code:gherkin

            - run: npm run build

            - run: npm run cucumber:undefined:step

            - run: npm run cucumber:unused:step
